#lang brag

program: payment*
payment: PAYMENT-TYPE NEXT-STEP-SYMBOL STRING NEXT-STEP-SYMBOL division
division: OPEN-DIVISION grouping CLOSE-DIVISION
grouping: OPEN-GROUPING STRING /COMMA NUMBER CLOSE-GROUPING (/COMMA grouping)*


