#lang brag

program: payment*
payment: PAYMENT-TYPE NEXT-STEP-OPERATOR STRING NEXT-STEP-OPERATOR division
division: OPEN-DIVISION grouping CLOSE-DIVISION
grouping: OPEN-GROUPING STRING NUMBER CLOSE-GROUPING (grouping)*
